name: go
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2
  share_plus: ^10.0.2
  web_socket_channel: ^3.0.1
  # barebones_timer:
  #   git:
  #     url: git@github.com:avnotaklu/barebones_timer.git
  #     ref: master

  barebones_timer:
    path: /home/ssp/dart/packages/barebones_timer

  ntp: ^2.0.0

  google_sign_in: ^6.2.1
  provider: ^6.0.1
  flutter_signin_button: ^2.0.0
  fpdart: ^1.1.0

  signalr_netcore:
    git:
      url: git@github.com:avnotaklu/signalr_client.git
      ref: master

  shared_preferences: ^2.3.2
  test: ^1.25.7
  mocktail: ^1.0.4
  responsive_framework: ^1.5.1
  google_sign_in_web: any
  http: any
  intl: ^0.20.1
  country_picker: ^2.0.27
  paginated_list: ^1.2.3

  # For hive
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  audioplayers: ^6.1.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/interface/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
    #       style: italic
    #     - asset: assets/fonts/Poppins/Poppins-Black.ttf
    #       style: italic
    #     - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
    #       style: italic
    #       weight: 700
    #     - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
    #       style: italic
    #       weight: 800
    #     - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
    #       style: italic
    #       weight: 200
    #     - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
    #       weight: 200
    #     - asset: assets/fonts/Poppins/Poppins-Italic.ttf
    #       style: italic
    #     - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
    #       style: italic
    #       weight: 300
    #     - asset: assets/fonts/Poppins/Poppins-Light.ttf
    #       weight: 300
    #     - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
    #       style: italic
    #       weight: 500
    #     - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    #     - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
    #       style: italic
    #       weight: 600
    #     - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
    #       style: italic
    #       weight: 100
    #     - asset: assets/fonts/Poppins/Poppins-Thin.ttf
    #       weight: 100

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/static/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        # - asset: assets/fonts/Nunito/static/Nunito-ThinItalic.ttf
        #   style: italic
        #   weight: 100
        # - asset: assets/fonts/Nunito/static/Nunito-Thin.ttf
        #   weight: 100


  #   - family: SpaceMono
  #     fonts:
  #       - asset: fonts/RobotoMono-Regular.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #         weight: 700
  # #
  # # For details regarding fonts from package dependencies,
  # # see https://flutter.dev/custom-fonts/#from-packages
