// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuzL-F-BcV4ZkO5K0jFkhNNX4U4MhRkWs',
    appId: '1:983500952462:web:ce655cdcbc4d138cff8adf',
    messagingSenderId: '983500952462',
    projectId: 'baduk-8a3a6',
    authDomain: 'baduk-8a3a6.firebaseapp.com',
    databaseURL: 'https://baduk-8a3a6-default-rtdb.firebaseio.com',
    storageBucket: 'baduk-8a3a6.appspot.com',
    measurementId: 'G-V39WFXCGPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKSJG5bNeWPERTocmlSm3hnmozJf_f5XQ',
    appId: '1:983500952462:android:a66be69fa119be6cff8adf',
    messagingSenderId: '983500952462',
    projectId: 'baduk-8a3a6',
    databaseURL: 'https://baduk-8a3a6-default-rtdb.firebaseio.com',
    storageBucket: 'baduk-8a3a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVcbo1XJ6dxjPjERi5CLFWAkRjOH4MYtg',
    appId: '1:983500952462:ios:35d211aeaf3dd354ff8adf',
    messagingSenderId: '983500952462',
    projectId: 'baduk-8a3a6',
    databaseURL: 'https://baduk-8a3a6-default-rtdb.firebaseio.com',
    storageBucket: 'baduk-8a3a6.appspot.com',
    androidClientId: '983500952462-d66piqv14tvkhftu7h4ifq531e813qqp.apps.googleusercontent.com',
    iosClientId: '983500952462-sma48q4m7rtb8ep88p93p8hlirme9lb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.go',
  );
}
